### ISSUE TITLE
[Feature Request} Cancel all orders for specific symbol

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-py#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Yes.
Support Request Ticket Number: 60289

Right now, there is no way to cancel all orders for specific symbol.
You can only cancel all orders `api.cancel_all_orders()`

### Describe the solution you'd like.

We need something like this:
`api.cancel_orders('AAPL')`

or something like this:
`api.cancel_all_orders('AAPL')`

or something like this:
`api.cancel_all_orders(symbol='AAPL')`

### Describe an alternate solution.

Keep it simple.

### Anything else? (Additional Context)

Keep it simple.

**Comment by sshcli** [comment]
Hey Mates!
Any news on this one?
At least can someone share an easy and simple workaround to this one?
Thanks in advance for your comments

**Comment by haxdds** [comment]
Hey @sshcli 

Although this feature would be nice, it isn't a priority for us at the moment. 
The best work around is to iterate through open orders and cancel each order with that symbol.

**Comment by haxdds** [comment]
Hey @sshcli 

Unfortunately, although it would be nice to have, it isn't a priority at the moment.

A work around is to fetch all open orders for that symbol and then cancel them.

It would look something like this

```python

filter =. GetOrdersRequest(symbols=["AAPL"])

orders = trading_client.get_orders(filter)

for o in orders:
    trading_client.cancel_order_by_id(o.id)

```

**Comment by sshcli** [comment]
> A work around is to fetch all open orders for that symbol and then cancel them.

Thanks, 
I have tested the above code with `alpaca-py(0.5.1)` adding `from alpaca.trading.requests import MarketOrderRequest ` and it works ok.

But...
I'm using `alpaca-trade-api (2.3.0)` in my algo/bot, I don't want to mix things
1. is there a similar solution for  `alpaca-trade-api (2.3.0)` ?
2. Do you recommend to start migrating to `alpaca-py(0.5.1)` ASAP?

Thanks in advance for your response.

Regards,

**Comment by sshcli** [comment]
> 1. is there a similar solution for `alpaca-trade-api (2.3.0) `?
> 2. Do you recommend to start migrating to `alpaca-py(0.5.1)` ASAP?

Forget it, I just saw the Deprecation Notice in the other repo. 
Great job !
Let's move forward
