### ISSUE TITLE
[Bug]: CryptoDataStream.subscribe_bars missing exchange for non raw_data output

### ISSUE THREAD

**Issue by secondvibe** [alpacahq/alpaca-py#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I use the default non raw_data in CryptoDataStream.subscribe_bars, it is missing the field exchange.  If I change it to raw_data, I can see the exchange.  I believe it is missing from the data/mappings.py and the data/models/bars.py.

### Expected Behavior

When I use the subscribe_bars, I expect one of the returned values for the record should indicate what exchange it is from.

### SDK Version I encountered this issue in

alpaca-py v0.5.0

### Steps To Reproduce

```markdown
Running on macOS Monterey 12.4, Python 3.9.10.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Hi @secondvibe, we recently updated our crypto data endpoints to `v1beta2`. 

https://alpaca.markets/docs/api-references/market-data-api/crypto-pricing-data/

Starting in `v1beta2`, crypto market data will no longer contain an `exchange` parameter in both queries and responses.

**Comment by secondvibe** [comment]
Will the quotes be coming from a single source?  I am getting two responses one from CSBE and one from FTXU, without the exchange response, I can't distinguish between the two.

**Comment by haxdds** [comment]
Crypto trading now happens on Alpaca's own venue. The crypto data provided is from activity on Alpaca's Orderbook.
