### ISSUE TITLE
[Bug]: TradingStream import missing in alpaca.trading.__init__

### ISSUE THREAD

**Issue by benlevitas** [alpacahq/alpaca-py#147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

TradingStream cannot be import due to a missing import in alpaca.trading.__init__

### SDK Version I encountered this issue in

alpaca-py version: 0.5.2

### Steps To Reproduce

```markdown
Try importing trading stream:
from alpaca.trading.stream import TradingStream
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Closed in #173
