### ISSUE TITLE
[Bug]: alpaca.trading.client compares list to List incorrectly

### ISSUE THREAD

**Issue by benlevitas** [alpacahq/alpaca-py#148]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In alpaca.trading.client there are multiple locations where a an object of type "list" is compared to "List".
For example in get_orders:
`if "symbols" in params and type(params["symbols"]) is List:`
will produce `False` even if symbols is a list.
Instead try using one of:

- isinstance(params["symbols"], list)
- type(params["symbols"]) is list
- type(params["symbols"]) == list

### SDK Version I encountered this issue in

0.5.2

### Steps To Reproduce

```markdown
Use function get_orders in alpaca.trading.client and pass a request with a list of symbols
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Closed in #174
