### ISSUE TITLE
[Question]: Why do you require pandas 1.3.5?

### ISSUE THREAD

**Issue by PBbanana** [alpacahq/alpaca-py#150]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

Is there a reason (a good reason) why this SDK requires pandas version 1.3.5?

I installed it yesterday to slowly ease into the new SDK. During installation, pandas was downgraded from 1.4.X to 1.3.5

This change broke my code. Turns out there are major improvements made to pandas since 1.3.5

**Comment by haxdds** [comment]
Hey @PBbanana thanks for bringing this up. We've updated the pandas requirement. 

Versions v0.5.5 and above reflect this change.
