### ISSUE TITLE
[Bug]: 1 validation error for Order legs -> 0 -> status

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-py#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to submit an OTO order, the order is submitted, but I get an error.

**The code I use to submit the OTO order:**
```
stock ='AAPL'
LO = LimitOrderRequest(symbol=stock, limit_price=188, qty=1, side=OrderSide.BUY, time_in_force=TimeInForce.GTC, order_class=OrderClass.OTO, take_profit=dict(limit_price=189) )
api.submit_order(order_data=LO)
```

**The error I get when the OTO order is submitted:**

```
1 validation error for Order
legs -> 0 -> status
  value is not a valid enumeration member; permitted: 'new', 'partially_filled', 'filled', 'done_for_day', 'canceled', 'expired', 'replaced', 'pending_cancel', 'pending_replace', 'accepted', 'pending_new', 'accepted_for_bidding', 'stopped', 'rejected', 'suspended', 'calculated' (type=type_error.enum; enum_values=[<OrderStatus.NEW: 'new'>, <OrderStatus.PARTIALLY_FILLED: 'partially_filled'>, <OrderStatus.FILLED: 'filled'>, <OrderStatus.DONE_FOR_DAY: 'done_for_day'>, <OrderStatus.CANCELED: 'canceled'>, <OrderStatus.EXPIRED: 'expired'>, <OrderStatus.REPLACED: 'replaced'>, <OrderStatus.PENDING_CANCEL: 'pending_cancel'>, <OrderStatus.PENDING_REPLACE: 'pending_replace'>, <OrderStatus.ACCEPTED: 'accepted'>, <OrderStatus.PENDING_NEW: 'pending_new'>, <OrderStatus.ACCEPTED_FOR_BIDDING: 'accepted_for_bidding'>, <OrderStatus.STOPPED: 'stopped'>, <OrderStatus.REJECTED: 'rejected'>, <OrderStatus.SUSPENDED: 'suspended'>, <OrderStatus.CALCULATED: 'calculated'>])
```

### Expected Behavior

The order should be submitted without any error.

### SDK Version I encountered this issue in

alpaca-py 0.5.4

### Steps To Reproduce

```markdown
Try to submit an OTO order with alpaca-py 0.5.4
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

Adding `order_status=OrderStatus.NEW` does not solve the problem

**Comment by dvddddddvd** [comment]
I have the same issue with bracket orders... turns out sometimes the API returns an OrderStatus of `'held'` which cannot be parsed.

**Comment by forLinDre** [comment]
Having the same issue with bracket orders. Will this issue be resolved anytime soon?

**Comment by yohay13** [comment]
having the same issue with bracket orders

**Comment by sshcli** [comment]
Attention @haxdds @drew887 we need your superpowers here.
Please help!

**Comment by drew887** [comment]
sorry @sshcli I no longer work for Alpaca and therefore am unable to help here. :sweat:

**Comment by sshcli** [comment]
> sorry @sshcli I no longer work for Alpaca and therefore am unable to help here. 😓

Understood. Thanks for the clarification.

**Comment by sshcli** [comment]
@impredicative thanks for let us know, I didn't receive the commit notification. I will test this tomorrow during market hours and post the update here.

**Comment by yohay13** [comment]
I will test it too

**Comment by sshcli** [comment]
Test results = ✔️ Pass
Thanks @OlegRa 

PS: IMHO, This issue can be closed as solved

**Comment by sshcli** [comment]
> @haxdds It is not clear why numerous GitHub issues weren't immediately updated after they were resolved, and a new released was out. Users struggle to know if they aren't informed. It is standard practice to keep users updated. Thanks.

Maybe @haxdds is too busy and have a huge amount of work. I'm here willing to join the Alpaca team as a tester and GitHub maintainer.

**Comment by haxdds** [comment]
@impredicative @sshcli 

Unfortunately, there's been a lack of maintenance and it's partly due to being spread kind of thin across a few projects. There will be an additional person starting to help maintain this repo so that should help a bit. 

Thank you @sshcli for testing the latest release! Any open source contributions would be very much appreciated.
