### ISSUE TITLE
Real time data during extended hours

### ISSUE THREAD

**Issue by kormoczi** [alpacahq/alpaca-py#155]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

Hi,
I am trying to get the real time data with the StockDataStream function. But I am not getting anything during extended hours.
I could not find anything in the documentation related to this issue...
Is there any parameter I need to provide? Or is it connected to the subscription level? Or is this not possible at all?
Thanks for your help!
Best regards,
Csaba

**Comment by haxdds** [comment]
Real time data during extended hours is only available for the SIP data feed. The SIP data feed is only available for the premium market data plan.
