### ISSUE TITLE
[Bug]: APIError.code() throws TypeError

### ISSUE THREAD

**Issue by ofb** [alpacahq/alpaca-py#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I produce an APIError e from alpaca.trading.client.TradingClient.submit_order(request).
I ask e.code() but it throws a TypeError:
This is probably a bug in alpaca-py, latest version.
from alpaca.common.exceptions import APIError
If e is an APIError, try asking for e.code. You get the following TypeError.
TypeError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/alpaca/common/exceptions.py in code(self)
     12     @property
     13     def code(self):
---> 14         return self._error["code"]
     15 
     16     @property

TypeError: string indices must be integers
The reason is that the error code is a string of json, and it hasn’t been parsed. Adding error = json.loads(e), you can then query error[‘code’].

Separately, it would be nice to have a ‘safe’ way to return e._error (which should be a dictionary but at least in my case is an unparsed string of JSON).

### Expected Behavior

Return an integer equal to the error code.

### SDK Version I encountered this issue in

0.6.0

### Steps To Reproduce

```markdown
See current behavior
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by mikenester** [comment]
I have the same issue, although i'm using `e.code` since `code` is a property. Here's a code snippet:

```python
from alpaca.trading.client import TradingClient
from alpaca.trading.requests import LimitOrderRequest

trading_client = TradingClient(
    "API-KEY", "API-SECRET", paper=True
)
limit_order_request = LimitOrderRequest(
        symbol="GDL.PRC",
        limit_price=48.64,
        qty=1,
        side=OrderSide.BUY,
        time_in_force=TimeInForce.DAY,
    )


limit_order = trading_client.submit_order(order_data=limit_order_request)
```

`submit_order` gets an `alpaca.common.exceptions.APIError`: `{"code":40010001,"message":"could not find asset \"GDL.PRC\""}`

When trying to handle the error in my code with:

```python
try:
    limit_order = trading_client.submit_order(order_data=limit_order_request)
        return limit_order
    except AlpacaAPIError as e:
        if e.status_code == 422:
            # unimportant

            if e.code == 40010001:
                # unimportant
```

`e.code` populates the`TypeError` @ofb mentioned. I tried the same solution in the `APIError` class and it worked

```python

import json


class APIError(Exception):
    # ...

    @property
    def code(self):
        print("\n---->>>self._error", self._error)
        error = json.loads(self._error)
        return error["code"]
```
