### ISSUE TITLE
[Bug]: Standardization of Crypto Ticker Format

### ISSUE THREAD

**Issue by forLinDre** [alpacahq/alpaca-py#179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using the trading client's get_open_position method, the crypto ticker format does not have to have a slash between symbols. For example "BTCUSD". The same applies for the position object. However when using other portions of the API the format requires a slash. For example, "BTC/USD".

### Expected Behavior

API should be standardized to use a slash between symbols such as "BTC/USD"

### SDK Version I encountered this issue in

alpaca-py version 0.6.0

### Steps To Reproduce

```markdown
1. acquire crypto position
2. use trading client's get_open_position method to acquire position
3. Note how method will not accept crypto ticker with "/" such as "BTC/USD" and requires format without slash ("BTCUSD")
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
This is an inconsistency issue that exists currently in the API. We're trying to keep the SDK 1-to-1 with the API, so we won't be fixing this on the client side and wait until it is fixed on the API side.

**Comment by haxdds** [comment]
@forLinDre In the meantime, one solution is to make a symbol converter on your own end that you feed into the client.

**Comment by forLinDre** [comment]
@haxdds, thanks for your response. I've been making it work with a conversion for now as you mentioned. Could this issue be reported to the folks maintaining the API? Or is there somewhere I can bring the issue up myself? 

Thanks,
Andrey
