### ISSUE TITLE
[Bug]: trading_client.get_all_assets() doesn't deliver 'maintenance_margin_requirement' attribute

### ISSUE THREAD

**Issue by alexanu** [alpacahq/alpaca-py#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do:
```
assets = trading_client.get_all_assets(GetAssetsRequest(asset_class=AssetClass.US_EQUITY,status= AssetStatus.ACTIVE))                              
assets[1]
```
I see this:
```
{   'asset_class': <AssetClass.US_EQUITY: 'us_equity'>,
    'easy_to_borrow': False,
    'exchange': <AssetExchange.BATS: 'BATS'>,
    'fractionable': False,
    'id': UUID('ff4089ed-12a6-4fa4-b6e2-3f5271741cd7'),
    'marginable': True,
    'name': 'Donoghue Forlines Yield Enhanced Real Asset ETF',
    'shortable': False,
    'status': <AssetStatus.ACTIVE: 'active'>,
    'symbol': 'DFRA',
    'tradable': True}
```
But in [API Docs it is written](https://alpaca.markets/docs/api-references/trading-api/assets/#equity-example) that Asset object contains also 'maintenance_margin_requirement'.

### SDK Version I encountered this issue in

alpaca-py version: 0.6.0

### Steps To Reproduce

```markdown
assets = trading_client.get_all_assets(GetAssetsRequest(asset_class=AssetClass.US_EQUITY,status= AssetStatus.ACTIVE))                              
assets[1]
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by forLinDre** [comment]
I am running into the same issue and would like to add that crypto assets should also contain "min_order_size", "min_trade_increment", and "price_increment" attributes according to Alpaca documentation (https://alpaca.markets/docs/api-references/trading-api/assets/).

**Comment by alexanu** [comment]
Hi, I see that this was just corrected by [this commit](https://github.com/alpacahq/alpaca-py/commit/3eb39a776feadf56abed6cdbf6bfa8c375cfe891) in master branch. Sorry for stupid question, but will be automatically available via pip install alpaca-py? I tried, but it is still not there.

**Comment by haxdds** [comment]
Hey @alexanu it will be available in the next release of alpaca-py `0.6.1`, which should be out either tonight or tomorrow sometime. If you want to use it earlier, you could clone the repo and import it as a module.

**Comment by alexanu** [comment]
Thanks for clarification, Rahul

**Comment by haxdds** [comment]
It's been released!

**Comment by alexanu** [comment]
Thank you. The clock() thing and assets work!

**Comment by forLinDre** [comment]
Hi, it looks like this commit did not resolve the fact that the crypto entity is still missing "min_order_size", "min_trade_increment", and "price_increment" attributes. Do I need to open a new issue or can this issue be reopened since it falls under the same umbrella? Thanks!
