### ISSUE TITLE
[Bug]: trading_client.get_all_assets() does not filter properly

### ISSUE THREAD

**Issue by MartinLPetrauskas** [alpacahq/alpaca-py#181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I do:

```python3
search_params = GetAssetsRequest(
    asset_status=AssetStatus.ACTIVE,
    asset_class=AssetClass.US_EQUITY,
)
assets = trading_client.get_all_assets(filter=search_params)
assets[0]
```

I see this:

```python3
{
id=UUID('28109ad7-5222-4331-ad85-23ac6e4d690e')
asset_class=<AssetClass.US_EQUITY: 'us_equity'>
exchange=<AssetExchange.OTC: 'OTC'>
symbol='SAKHD' name='Rafex Gold Corp. Common Stock'
status=<AssetStatus.INACTIVE: 'inactive'>
tradable=False
marginable=False
shortable=False
easy_to_borrow=False
fractionable=False
}
```

In the [API Docs ](https://alpaca.markets/docs/python-sdk/trading.html#trading) it says filtering is allowed by AssetStatus, AssetClass, and AssetExchange. However, in the above example, I see an 'inactive' when I specifically filtered for 'active'

### Expected Behavior

When I do:

```python3
search_params = GetAssetsRequest(
    asset_status=AssetStatus.ACTIVE,
    asset_class=AssetClass.US_EQUITY,
)
assets = trading_client.get_all_assets(filter=search_params)
assets[0]
```

I should be seeing `status=<AssetStatus.ACTIVE: 'active'>` in the asset

### SDK Version I encountered this issue in

alpaca-py version: 0.6.0

### Steps To Reproduce

```markdown
Environment: Python3.9 & alpaca-py 0.6.0

Run the following code:

#! /usr/bin/env python3.9

from alpaca.trading.client import TradingClient
from alpaca.trading.requests import GetAssetsRequest
from alpaca.trading.enums import AssetClass, AssetStatus

trading_client = TradingClient(api_key, secret_key, paper=True)

search_params = GetAssetsRequest(
    asset_status=AssetStatus.ACTIVE,
    asset_class=AssetClass.US_EQUITY,
)
assets = trading_client.get_all_assets(filter=search_params)
print(assets[0])
```

Additional Code to verify 'inactive' assets showing when specifically filtering for 'active' assets:

```python3
assets = trading_client.get_all_assets(filter=search_params)
inactive_assets = [a for a in assets if a.status == AssetStatus.INACTIVE]
print(len(inactive_assets))
print(inactive_assets[0])
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by jcoffi** [comment]
change `asset_status=AssetStatus.ACTIVE,` to `status=AssetStatus.ACTIVE,` and you should be good to go

**Comment by MartinLPetrauskas** [comment]
@jcoffi That change worked. Can't believe I overlooked that typo. Thanks for pointing it out.
