### ISSUE TITLE
[Bug]: Market Data API - Random Server Outages?

### ISSUE THREAD

**Issue by anpunjabi** [alpacahq/alpaca-py#183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have been using the market data api with an unlimited subscription. Specifically, I have been using the alpaca-py SDK and trying to get historical data for about 500 companies during a given time period. I run a request in the following format:

```
request_params = StockBarsRequest(
                        symbol_or_symbols=tick_list,
                        timeframe=timeframe.TimeFrame(30, timeframe.TimeFrameUnit['Minute']),
                        start=datetime.datetime.now(tz=pytz.timezone("UTC"))-datetime.timedelta(30),
                        end=datetime.datetime.now(tz=pytz.timezone("UTC"))
                 )
bars = alpaca_client.get_stock_bars(request_params)
```

where tick_list is a list of strings corresponding to stock tickers. In many instances, I get an internal server error like this one:

`{"code":50010000,"message":"internal server error occurred"}`

However, this does not always occur. For example, I ran this same query a few moments later and it ran fine. Is there a rate limit that I am hitting? If so, I would have expected to get a 429 error. The status page (https://status.alpaca.markets/) didn't seem to indicate any server outage either. Does anyone know what might be going on?

### SDK Version I encountered this issue in

0.6.0

### Steps To Reproduce

```markdown
1. Set up StockBarsRequest with query tickers, timeframe, start and end data
2. Run alpaca_client.get_stock_bars
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
This was due to an API issue that happened yesterday.
