### ISSUE TITLE
[Feature Request] GTC + EXT

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-py#190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Yes, there is a problem.
We are not able to open/close positions with GTC orders on extended hours.
There are other brokers that allows you to do this.

### Describe the solution you'd like.

There are several brokers, including TD Ameritrade, that already support orders `GTC + EXT`
Alpaca is now able to trade in full extended hours (4:00 AM - 8:00 PM EST) Great!
But is not enough, as a customer, we also need the possibility of using `GTC + EXT`
I'm sure there are a lot of traders that will thank you for this.

If this is something that goes beyond your jurisdiction or need to be escalated, please forward it to the appropriate team.

### Describe an alternate solution.

An alternate solution could be the ability to replace the order during extended hours without having the error:
`pending_cancel`

### Anything else? (Additional Context)

Occam's razor | keep it simple

**Comment by sshcli** [comment]
> Although the issue is quite important, personally I have been reluctant to file such issue here because this repo is just the Python SDK, not the backend. The issue applies first to the backend.

Hi @impredicative, I perfectly understand your point and I agree with you.
The problem is:
This is the only official repo with recent activity and some responses.
The right repo for this kind of features ( https://github.com/alpacahq/Alpaca-API ) has almost two years without any commit. 

I'm just trying to get the attention of any Alpaca Developer capable of implementing this feature.
Blue car, red car, white car, we don't care, We just need a car.

**Comment by haxdds** [comment]
I've brought it up internally as a suggested change to the API - there are no current plans on making this available.

**Comment by sshcli** [comment]
Ok @haxdds 
Thanks anyway for your efforts
