### ISSUE TITLE
StockDataStream does not work within Jupyter notebook- RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by eddietaylor** [alpacahq/alpaca-py#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Trying to develop an open source python wrapper around alpaca-py and I'm mainly developing in Jupyter notebooks. When it comes to streaming data, everything works fine with .py files until you try to run the wss client within a jupyter notebook. Apparently, this is a problem with notebooks because they are already running an event loop. 

### Describe the solution you'd like.

I don't know much about asynchronous functions and streaming so I can't really offer a solution.

**Comment by sshcli** [comment]
try to leave the data stream out of the loop, and call it from a function within the loop

**Comment by haxdds** [comment]
Hi @eddietaylor 

Running asyncio loops are a bit weird in jupyter notebooks

Another solution in addition to sshcli's is to use `nest_asyncio`

Here is a post on stackoverflow that discusses it

https://stackoverflow.com/a/63539722
