### ISSUE TITLE
asset object should contain the asset's INITIAL margin requirement

### ISSUE THREAD

**Issue by forLinDre** [alpacahq/alpaca-py#194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The current asset object only provides the maintenance margin requirement for a US equity and not the initial margin requirement. How can I implement a check to ensure that I have enough equity for an order if I only know the maintenance margin requirement which is usually lower than the initial margin requirement? 

### Describe the solution you'd like.

The asset object requested via the trading client would contain both the maintenance margin requirement as it currently does as well as the initial margin requirement.

### Anything else? (Additional Context)

This problem has been voiced by the community as well and has led to margin calls. Specifically Mr_drawdown has commented "Just today I had to contact Alpaca customer service wondering why I received a margin call on a day I was net green. Currently it seems the software allows you to enter into trades beyond what your initial margin can actually support, but then later it detects something is off by checking maintenance margin."  I am not sure if the software still allows you to enter a position that does not adhere to initial margin requirements but either way, the value should be communicated to the user. Here is the community forum link: [https://forum.alpaca.markets/t/api-for-stock-margin-requirement/2435/7]

If i am missing a feature that is already implemented to resolve this, please let me know! I noticed that the account object has the initial margin requirement information but I don't really understand how to use it since the requirement is different for each asset...

**Comment by haxdds** [comment]
Hi @forLinDre 

Thanks for contributing

I've resurfaced this issue within our team - but in the meantime since this is an issue that needs to be solved at the API level, I will close this issue. If there are any updates I'll keep you posted on this thread.
