### ISSUE TITLE
[Question]: What is the purpose of the order type parameter in StopLimitOrderRequest?

### ISSUE THREAD

**Issue by eddietaylor** [alpacahq/alpaca-py#197]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

What is the purpose of specifying the order type when this is implicit in the choice of request class object? If I am using StopLimitOrderRequest, then I am doing a stop limit order.

**Comment by haxdds** [comment]
It is not meant to be used. Since `StopLimitOrderRequest`  inherits from `OrderRequest`, it inherits the `type` parameter. If you try to use that parameter in `StopLimitOrderRequest`, it will simply be overwritten.
