### ISSUE TITLE
[Bug]: Invalid Order Type for Crypto Order 

### ISSUE THREAD

**Issue by eddietaylor** [alpacahq/alpaca-py#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have tried creating a stop order for BTC/USD, with the following documentation code adapted to stop orders:

`stop_order_data = StopOrderRequest(
                    symbol='BTC/USD',
                    stop_price=21900.50,
                    qty=.5,
                    side="sell",
                    time_in_force="gtc",
                    type="stop" 
                   )

stop_order = trade_inst.trading_client.submit_order(
                order_data=stop_order_data
            )`

I have tried these lines of code for all of the order types and get the same error of "invalid order type for crypto order"

Are stop orders not supported for crypto securities? 

### Expected Behavior

I have tested the market order and limit order methods (they work) and the expected behavior would be the same, namely, reflection of the order in the dashboard as well as in the account if it fills. 

### SDK Version I encountered this issue in

alpaca-py version: 0.6.1

### Steps To Reproduce

```markdown
1. In jupyter notebook of vs code, running python 3.7.3
2. import the necessary packages 
3. connect to your paper account with api and secret keys
3. run the above code
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Hey Eddie,

Currently, crypto only supports `market`, `limit`, `stop limit` order types. That is why you are receiving the error.

Best
Rahul
