### ISSUE TITLE
[Question]: How does get_portfolio_history_for_account() works?

### ISSUE THREAD

**Issue by alexanu** [alpacahq/alpaca-py#217]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

Hi all,

I was trying to get the portfolio history of my account:
```
account_id = trading_client.get_account().id
data_pf = broker_client.get_portfolio_history_for_account(account_id)

```
..But somehow I receive:
``requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://broker-api.alpaca.markets/v2/trading/accounts/XXXXXXX-XXXXX-XXXXX-XXXX-XXXXXXXXXX/account/portfolio/history`
`Could you pls advice what I'm doing wrong? All other things works smoothly.

**Comment by haxdds** [comment]
Hi @alexanu

This `get_portfolio_history_for_account` method you are using is for the [Broker API.](https://alpaca.markets/broker)

Right now, we don't support portfolio history for trading api because it is currently under a rework. Once portfolio history V2 is complete, we will create the corresponding method within the trading client.

**Comment by tomnewg** [comment]
what is the status for portfolio history on the trading api? Many thanks

**Comment by nickvertucci** [comment]
@haxdds Any update on portfolio histoy V2?

**Comment by hiohiohio** [comment]
@nickvertucci portfolio histoy V2 was rolled out for trading api.
Adding portfolio history into trading api client is in my backlog.
