### ISSUE TITLE
[Question]: How many symbols can be requested for StockBarsRequests at once and is it asynchronous?

### ISSUE THREAD

**Issue by jihun-yoon** [alpacahq/alpaca-py#222]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [ ] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

How many symbols can be requested for `StockBarsRequests` at once?

For example, the following codes request Bars for AAPL and GOOG
```
request_params = StockBarsRequest(
                        symbol_or_symbols=["AAPL", "GOOG"],
                        timeframe=TimeFrame.Day,
                        start=datetime.strptime("2022-07-01", '%Y-%m-%d')
                 )
```

And is it asynchronous?

**Comment by haxdds** [comment]
Hi you can learn about any data limits here

https://alpaca.markets/data

and currently the calls are not asynchronous.
