### ISSUE TITLE
[Bug] Error handling for no buying power 

### ISSUE THREAD

**Issue by sshcli** [alpacahq/alpaca-py#225]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

You get an error and the app breaks when you don't have enough buying power 

### Expected Behavior

You should get a message or value indicating you don't have enough buying power (without breaking the app)

### SDK Version I encountered this issue in

Tested with `alpaca-py 0.6.1`

### Steps To Reproduce

```markdown
1. Try to buy more than you are allowed
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Hi @sshcli ,

I'm not able to reproduce your issue. 

When I try to submit a similar order, I receive

```APIError: {"buying_power":"176531.28","code":40310000,"cost_basis":"48640000","message":"insufficient buying power"}```

Can you try your request again with `0.7.0`?

**Comment by sshcli** [comment]
Hi @haxdds 
False alarm.
I can confirm that it is working as expected in both `0.6.1` and `0.7.0 `
Maybe it was something else causing the error or my mistake.
I'm closing this one as solved.

Thanks
