### ISSUE TITLE
[Bug]: initialize TimeFrame for 15 Min, get 151 Min

### ISSUE THREAD

**Issue by mrticker** [alpacahq/alpaca-py#243]
You can initialize TimeFrame like this by mistake:

`tf = TimeFrame( 15, TimeFrame.Minute )    # should be TimeFrameUnit.Minute`

And it will pass validation and result in weird behaviour, as the value of  tf will be '151Min'.

**Comment by mzaeemnasir** [comment]
I fixed it Try to use 

`from alpaca.data.timeframe import TimeFrame, `TimeFrameUnit
tf = TimeFrame( 15, TimeFrame.Minute ) `
