### ISSUE TITLE
error during websocket communication: connection limit exceeded

### ISSUE THREAD

**Issue by mzaeemnasir** [alpacahq/alpaca-py#248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While Connecting with the StockDataStream I am getting this error

### SDK Version I encountered this issue in

 alpaca-py 1.0.4

### Steps To Reproduce

```markdown
Simple wss_client.subscribe_bars(fun, "QQQ")
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by sshcli** [comment]
alpaca-py 1.0.4 ????

As far as I know, the latest version available is `alpaca-py 0.7.1`

**Comment by mzaeemnasir** [comment]
Sorry My bad 

![image](https://user-images.githubusercontent.com/53820312/219588641-ebcc845f-1763-4faa-b072-463665f4534c.png)

**Comment by Jmarkaba** [comment]
I am having the same issue (connection limit exceeded/auth error message) with the subscribe_quotes function on the websocket. I am not sure if it's an issue with having a free paper trading account or not
