### ISSUE TITLE
[Bug]: Pydantic validation errors for firm accounts

### ISSUE THREAD

**Issue by alessiocastrica** [alpacahq/alpaca-py#254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I get the sweep account from the broker client it returns validation errors because the date_of_birth and tax_id_type attributes in the account should be nullable. 
![Screenshot 2023-03-03 at 19 57 21](https://user-images.githubusercontent.com/104512673/222804059-a7e3cef8-6639-4e4a-8a49-312411582da4.png)

### Expected Behavior

Make optional date_of_birth and tax_id_type attributes in the account model.

### SDK Version I encountered this issue in

alpaca-py version 0.7.1

### Steps To Reproduce

```markdown
Use the broker client to retrieve a sweep account by ID using the method get_account_by_id
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
closed by #255
