### ISSUE TITLE
Include the asof parameter for historical stock data requests

### ISSUE THREAD

**Issue by didriknielsen** [alpacahq/alpaca-py#256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The API references describe an `asof` parameter: 
https://alpaca.markets/docs/api-references/market-data-api/stock-pricing-data/historical/

However, this is not included in the various requests `StockBarsRequest`, `StockTradesRequest`, `StockQuotesRequest`, etc. of `alpaca-py`. 

The same goes for the `currency` parameter.

### Describe the solution you'd like.

Implement the `asof` (and `currency`) parameters in `StockBarsRequest`, `StockTradesRequest`, `StockQuotesRequest`, etc.

**Comment by hiohiohio** [comment]
This issue is resolved by https://github.com/alpacahq/alpaca-py/pull/477
