### ISSUE TITLE
[Bug]: Different `submitted_at` from `submit_order` and `get_order_by_id` 

### ISSUE THREAD

**Issue by zepedaj** [alpacahq/alpaca-py#261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The order object returned by `TradingClient.submit_order` and `TradingClient.get_order_by_id` for the same order have different values for `Order.submitted_at`. In the example below, the values are, respectively

* 2023-03-20 17:03:02.000456+00:00 
* 2023-03-20 17:03:02.010772+00:00

Here is a MNWE:

```
        from alpaca.trading.requests import OrderRequest
        from alpaca.trading.enums import OrderSide, OrderType, TimeInForce

        # trading_client = alpaca.trading.client.TradingClient(<api_key>, <secret_key>)
        submitted_order = trading_client.submit_order(
            OrderRequest(
                symbol="AMZN",
                qty=1,
                side=OrderSide.BUY,
                type=OrderType.MARKET,
                time_in_force=TimeInForce.GTC,
            )
        )

        retrieved_order = trading_client.get_order_by_id(submitted_order.id)

        print(submitted_order.submitted_at, retrieved_order.submitted_at)

        assert submitted_order.submitted_at == retrieved_order.submitted_at
```

### Expected Behavior

Both methods should return an `Order` object with the same  `Order.submitted_at` value.

### SDK Version I encountered this issue in

alpaca-py version: 0.6.1

### Steps To Reproduce

```markdown
(See the MNWE above.)
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
The issue most likely has to do with how the order data is later stored in the database. I'm closing this since it's not related to the SDK and is more about the API's behavior.

**Comment by haxdds** [comment]
If you'd like to learn more about this - I'd ask this question on the forums or slack channel.

https://forum.alpaca.markets/
