### ISSUE TITLE
[Bug]: `Order.submitted_at` differs when retrieved with `get_orders` or `get_order_by_id`

### ISSUE THREAD

**Issue by zepedaj** [alpacahq/alpaca-py#262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

(Possibly related to [261](https://github.com/alpacahq/alpaca-py/issues/261)) 

When retrieving a newly submitted order with  `TradingClient.get_orders` or `TradingClient.get_order_by_id`, the resulting `Order.submitted_at` attribute of the two returned `Order`  objects sometimes match and sometimes differ by *1 us*, with `get_orders` producing an `Order.submitted_at` value that is **1** *us* later, e.g.:

* `Order.submitted_at` from `get_order_by_id`: *2023-03-20 22:55:40.968014+00:00*
* `Order.submitted_at` from `get_orders`: *2023-03-20 22:55:40.968015+00:00*

```
# trading_client = alpaca.trading.client.TradingClient(<api_key>, <secret_key>)
submitted_order = trading_client.submit_order(
    OrderRequest(
        symbol="AMZN",
        qty=1,
        side=OrderSide.BUY,
        type=OrderType.MARKET,
        time_in_force=TimeInForce.GTC,
    )
)

# 1) Order `submitted_order` does not immediately appear in results of `get_orders`.
while True:
    try:
        order_from_get_orders = [
            x
            for x in trading_client.get_orders(
                GetOrdersRequest(status="all", limit=500)
            )
            if x.id == submitted_order.id
        ][0]
        break
    except:
        sleep(1)

# 2) Order from `get_orders` and `get_order_by_id` have different `submitted_at` values randomly
order_from_get_order_by_id = trading_client.get_order_by_id(
    submitted_order.id
)
assert (
    order_from_get_order_by_id.submitted_at
    == order_from_get_orders.submitted_at
)
```

### Expected Behavior

The values of `order_from_get_order_by_id.submitted_at` and `order_from_get_orders.submitted_at` should be the same.

### SDK Version I encountered this issue in

alpaca-py version: 0.6.1

### Steps To Reproduce

```markdown
See MNWE above.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
duplicate
