### ISSUE TITLE
[Bug]: Python3.11 Support

### ISSUE THREAD

**Issue by haxdds** [alpacahq/alpaca-py#271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Enums are not being converted to their proper values.

### SDK Version I encountered this issue in

v0.8.1

### Steps To Reproduce

```markdown
Try market data or REST API endpoints using python3.11.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Related Issues:

https://github.com/alpacahq/alpaca-py/issues/271

**Comment by alessiocastrica** [comment]
Supported from v0.11
