### ISSUE TITLE
[Question]: European Exchanges and missing of exchange parameters in the SDK

### ISSUE THREAD

**Issue by kadnan** [alpacahq/alpaca-py#279]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

Sorry for asking two questions in one issue.

- In Official [API](https://alpaca.markets/docs/api-references/trading-api/assets/) when you query `/assets`, you can mention the `exchange` but this is not available in the SDK's function `list_assets`. If I go to the function's signature I find this:
```
 def list_assets(self, status=None, asset_class=None) -> Assets:
        """Get a list of assets"""
        params = {
            'status':      status,
            'asset_class': asset_class,
        }
        resp = self.get('/assets', params)
        if self._use_raw_data:
            return resp
        else:
            return [self.response_wrapper(o, Asset) for o in resp]
```

As you can see, it is assumed it is for US exchanges hence missing.

My question is, can't I use Alpaca for German exchanges?

**Comment by haxdds** [comment]
Alpaca only provides stocks on US exhanges at the moment.
