### ISSUE TITLE
[Bug]: `currency` field on `alpaca.broker.journal.Journal` object should be `Optional`

### ISSUE THREAD

**Issue by br-follow** [alpacahq/alpaca-py#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we fetch journals from the API via `get_journal_by_id`, parsing them into `Journal` objects fails with a `ValidationError`

```
1 validation error for Journal
currency
  field required (type=value_error.missing)
```

### Expected Behavior

`currency` should be optional or it should default to USD, which is what the docs indicate `None` represents.

### SDK Version I encountered this issue in

0.8.1

### Steps To Reproduce

```markdown
Fetch a journal and parse it into a `Journal` object
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
Closed due to no further response from user
