### ISSUE TITLE
[Bug]: Quote requests throw attribute error when no quotes are available

### ISSUE THREAD

**Issue by danboyle7** [alpacahq/alpaca-py#282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I make a StockQuoteRequest (or Crypto), and there are no quotes available within the start/end timeframes, the code is unable to properly handle empty item and it throws an exception:
```
File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/<project>/lib/python3.9/site-packages/alpaca/data/historical/stock.py", line 125, in get_stock_quotes
    return QuoteSet(raw_quotes)
  File "/Users/<user>/Library/Caches/pypoetry/virtualenvs/<project>/lib/python3.9/site-packages/alpaca/data/models/quotes.py", line 73, in __init__
    parsed_quotes[symbol] = [Quote(symbol, quote) for quote in quotes]
  File /Users/<user>/Library/Caches/pypoetry/virtualenvs/<project>/lib/python3.9/site-packages/alpaca/data/models/quotes.py", line 73, in <listcomp>
    parsed_quotes[symbol] = [Quote(symbol, quote) for quote in quotes]
  File /Users/<user>/Library/Caches/pypoetry/virtualenvs/<project>/lib/python3.9/site-packages/alpaca/data/models/quotes.py", line 48, in __init__
    for key, val in raw_data.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

### Expected Behavior

Should return an empty item, or atleast a valid exception, as opposed to trying to do an operation on a NoneType object.

For this example, get_stock_quotes should ensure that it is passing a valid raw_quotes object to QuoteSet.

### SDK Version I encountered this issue in

0.7.1 (Checked most recent and it is still issue)

### Steps To Reproduce

```markdown
1. Create client via StockHistoricalDataClient
2. Create StockQuotesRequest for a small time interval (lets say 1 minute ago UTC, to now UTC) -- easiest to reproduce during after-hours on a US stock. May take a couple attempts.
3. Submit request via get_stock_quotes function in the client.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

Important to note this occurs for both stock/crypto requests. 

UPDATE: Also occurs when it fails to obtain bars.

**Comment by advancetogo** [comment]
I've encountered the same issue, here are a few example symbols I've identified that this issue has occurred with. ('ATMCR', 'ATMVR', 'BHRB')

**Comment by Tadimsky** [comment]
Having the same issue - it looks like we have an array of one `None` element instead of an empty array.

<img width="1920" alt="Screenshot 2023-05-31 at 09 00 13" src="https://github.com/alpacahq/alpaca-py/assets/1149244/5451d4ac-a708-4704-8734-1f8065d854ae">

The raw response from the API is:
```json
{"bars":null,"symbol":"COIN","next_page_token":null}
```

And so this code is parsing the `null` into `None` and adding to to a list.
response_data.items()

**Comment by haxdds** [comment]
cleaning up some issues since there are duplicates

follow along here
https://github.com/alpacahq/alpaca-py/issues/317
