### ISSUE TITLE
[Bug]: CorporateActionAnnouncement  - too many non-optional fields

### ISSUE THREAD

**Issue by mike-greenmmd** [alpacahq/alpaca-py#291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The pydantic data model on class CorporateActionAnnouncement seems like it has too many non-optional fields.
I'm getting errors on `initiating_symbol`, `initiating_original_cusip`, `target_symbol` & `target_original_cusip` 
when tryting to pull stock splits, but there could be more. See reproducing steps...

Would be great if you could harmonize this with your database model!

```
CorporateActionAnnouncement(BaseModel):
    id: UUID
    corporate_action_id: str
    ca_type: CorporateActionType
    ca_sub_type: CorporateActionSubType
    **initiating_symbol: str**
    **initiating_original_cusip: str**
    **target_symbol: str**
    **target_original_cusip: str**
    declaration_date: Optional[date]
    ex_date: Optional[date]
    record_date: date
    payable_date: date
    cash: float
    old_rate: float
    new_rate: float
```

### SDK Version I encountered this issue in

alpaca-py: 0.8.2

### Steps To Reproduce

```markdown
request_params = GetCorporateAnnouncementsRequest(
                                                      ca_types = [CorporateActionType.SPLIT]
                                                      since = datetime(2023,2,1),
                                                      until = datetime(2023,5,1)
                                                     )
splits = trading_client.get_corporate_announcements(request_params)
```

fails with error
```
ValidationError: 50 validation errors for ParsingModel[List[alpaca.trading.models.CorporateActionAnnouncement]]
__root__ -> 6 -> target_symbol
  field required (type=value_error.missing)
__root__ -> 6 -> target_original_cusip
  field required (type=value_error.missing)
```
```


### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

_No response_

**Comment by brunerm99** [comment]
Running into this error as well. It seems like the `target_symbol` and `target_original_cusip` fields should be made optional in the `CorporateActionAnnouncement` model to fix this bug. Seems like two important fields though. 

Wondering if events should just ignored if they don't contain these fields or if they're useful for something I'm not aware of?
