### ISSUE TITLE
The SDK is too big to package it to AWS Lambda

### ISSUE THREAD

**Issue by etishka** [alpacahq/alpaca-py#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

alpaca-py has some dependencies which are consuming a lot of disk space. 

Packaged projects quickly run out of 250MB allowed by Lambda. This makes it impossible to deploy applications using alpaca-py SDK to AWS Lambda. 

Previous SDK (alpaca-trader-api) was much slimmer and there were no problems deploying it to Lambda.

Please produce a slim version of SDK

**Comment by haxdds** [comment]
We don't have any plans of publishing a light weight version of the SDK. If you wish, you can hack together the SDK code you need into your own fork of the library which you can use.
