### ISSUE TITLE
[Bug]: Issue with Crypto Data Stream URL

### ISSUE THREAD

**Issue by devthakker** [alpacahq/alpaca-py#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I try to subscribe to any kind of crypto data stream I see the the response :
"data websocket error, restarting connection: server rejected WebSocket connection: HTTP 404"

### Expected Behavior

I expected the data stream to be coming in here from the web socket.

When I subscribe to quotes is should be something like this:
"symbol='BTC/USD' timestamp=datetime.datetime(2023, 6, 4, 21, 28, 56, 294326, tzinfo=datetime.timezone.utc) ask_exchange=None ask_price=27281.6 ask_size=0.55877446 bid_exchange=None bid_price=27244.490389 bid_size=0.27643693 conditions=None tape=None"

### SDK Version I encountered this issue in

alpaca-py version: 0.8.2

### Steps To Reproduce

```markdown
from alpaca.data.live import CryptoDataStream

crypto_data_client = CryptoDataStream(KeyPaper, SecretKeyPaper)

async def quote_data_handler(data: any):
    print(data)

crypto_data_client.subscribe_quotes(quote_data_handler, "BTC/USD")

crypto_data_client.run()
```

### Filled out the Steps to Reproduce section?

- [x] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

This issue can be resolved with the url override to the correct endpoint

from alpaca.data.live import CryptoDataStream

crypto_data_client = CryptoDataStream(KeyPaper, SecretKeyPaper, url_override="wss://stream.data.alpaca.markets/v1beta3/crypto/us")

async def quote_data_handler(data: any):
    print(data)

crypto_data_client.subscribe_quotes(quote_data_handler, "BTC/USD")

crypto_data_client.run()

**Comment by haxdds** [comment]
This is related to this issue:
