### ISSUE TITLE
Update to pydantic v2

### ISSUE THREAD

**Issue by impredicative** [alpacahq/alpaca-py#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

pydantic v2 offers better performance than v1. As such, it doesn't make sense to stick to v1.

**Comment by alessiocastrica** [comment]
@haxdds I agree with this issue, v2 is approx 20 times faster, made a [PR](https://github.com/alpacahq/alpaca-py/pull/315).
