### ISSUE TITLE
Update websockets to v11

### ISSUE THREAD

**Issue by impredicative** [alpacahq/alpaca-py#307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Sometimes there are random errors when using `websockets`. Currently the version v10 is used. The goal is for the rate of errors to be minimized via the use of v11 of the `websockets` package.

**Comment by alessiocastrica** [comment]
@impredicative thanks for flagging this, [I made a PR](https://github.com/alpacahq/alpaca-py/pull/322).

**Comment by haxdds** [comment]
Fixed in 0.9.0

**Comment by haxdds** [comment]
Sorry that's my mistake I thought we had merged it but it's currently in the `staging` branch. See #316

**Comment by alessiocastrica** [comment]
Fixed in 0.11
