### ISSUE TITLE
[Question]: How to get the daily profit/loss of a single stock？

### ISSUE THREAD

**Issue by cgntiger** [alpacahq/alpaca-py#310]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

I use alpaca-py's TradingClient, I can only get the unrealized profit and loss in the position, I can't get the daily profit directly, and I can't get the realized profit and loss. Do I need to pull the transaction data from 0:00 New York time? Calculate realized profit and loss? Then track new trades, thus updating the realized profit and loss? Then daily profit = realized profit and loss + unrealized profit and loss?
Do you have a ready-made api or other simple solutions to calculate the daily profit of a single stock?

**Comment by haxdds** [comment]
Closing since this issue isn't related to the API. Please ask this on the [alpaca forums](https://forum.alpaca.markets/).
