### ISSUE TITLE
[Bug]: setup.py file missing after v0.8.0

### ISSUE THREAD

**Issue by darose** [alpacahq/alpaca-py#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

setup.py file is missing from the downloads for version 0.8.1 and .2 over at the PyPi site (https://pypi.org/project/alpaca-py/) 

### Expected Behavior

setup.py file is present in the download for versions 0.8.0 and earlier, and so should (I think) be present for later versions.

### SDK Version I encountered this issue in

version 0.8.1 and later

### Steps To Reproduce

```markdown
1. Download the source for version 0.8.2 from the PyPi site (https://files.pythonhosted.org/packages/95/9a/c866d3091981080489f14171b69712fa22c65dcb09c2888eca936fa89cd8/alpaca_py-0.8.2.tar.gz)
2. Un-tar the download
3. Observe that there is no setup.py file present in the download
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

I've been maintaining the alpaca-py package over at Arch Linux. (https://aur.archlinux.org/packages/python-alpaca-py)

I've been using the provided setup.py file as part of the package build process.  That setup.py file has worked fine up through v0.8.0. However, I noticed that the downloads for version 0.8.1 and .2 over at the PyPi site (https://pypi.org/project/alpaca-py/) no longer supply the setup.py file.

Is that an unintentional omission?
* If so, then can you please update/fix at the PyPi site to include the setup.py file once again?
* If not, then can you please explain the proper way for packagers to build the package now, without the setup file?

**Comment by haxdds** [comment]
This wasn't intended - I will take a look

**Comment by darose** [comment]
Are there any plans to fix this?  I see that the recently released v0.10.0 doesn't contain a setup.py file either.  The missing setup file is preventing me from upgrading this package at Arch Linux, keeping it several versions behind.  (https://aur.archlinux.org/packages/python-alpaca-py)

**Comment by darose** [comment]
> Are there any plans to fix this? I see that the recently released v0.10.0 doesn't contain a setup.py file either. The missing setup file is preventing me from upgrading this package at Arch Linux, keeping it several versions behind. (https://aur.archlinux.org/packages/python-alpaca-py)

Hello?  Is this bug going to be fixed?  Seems like a simple issue to correct, but it's been open for 2 months.

**Comment by darose** [comment]
@alessiocastrica ?

**Comment by alessiocastrica** [comment]
Hi @darose sorry for the delay, can I ask you why you're relying on downloading the source code from PyPI and the setup.py file there? 
You should be able to use the `poetry.lock` and `pyproject.toml` for the dependencies specification and you can easily convert them into a requirements.txt file if you want to use pip directly instead of poetry.

**Comment by darose** [comment]
As I wrote above, I've been maintaining the alpaca-py package over at Arch Linux. (https://aur.archlinux.org/packages/python-alpaca-py).  I've been maintaining this package so that everyone in the Arch community can easily install and use alpaca-py   (which I use as well) via Arch's "pacman" package manager.  So that precludes doing the installation using pip.

When I first started maintaining the package, the PyPI download included a setup.py file.  So I tried using that (see https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-alpaca-py#n18) which worked, and made the package easy to build.

As I wrote above: "[if using setup.py is no longer the correct way to build the package] can you please explain the proper way for packagers to build the package now, without the setup file?"  It sounds like you're suggesting that I should now use poetry.lock and/or pyproject.toml to do the build instead of setup.py.  Is that correct?  If so, would you be able to suggest how to use those to build the package?  (My apologies, I'm not familiar with poetry or pyproject files.)

**Comment by alessiocastrica** [comment]
Hi @darose thanks for the details. 
For context, we've used poetry from the beginning to manage this package dependencies, and as far as I know, we never intended to maintain a separate `setup.py` to build the package. 
Can you please try to follow [section 4.1 of Python package guidline](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_.28PEP_517.29) for building Python package using `pyproject.toml` instead of `setup.py`? 
Let me know if that works.

**Comment by darose** [comment]
Looks all good!

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-alpaca-py

```
$ pacman -Q python-alpaca-py
python-alpaca-py 0.11.0-1
```

Thanks much for the fix!  (And the pointers.)
