### ISSUE TITLE
[Question]: Unable to get max buying power after liquidating all my assets

### ISSUE THREAD

**Issue by DanishjeetSingh** [alpacahq/alpaca-py#312]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question
```python

trading_client = TradingClient(api_key=config['ALPACA']['api_key'], secret_key=config['ALPACA']['secret_key'], paper=True)

liquidate = trading_client.close_all_positions(cancel_orders=True)

account = trading_client.get_account()
```

above is my code, i liquidate all my assets so I can have the max buying power, but it doesn't seem to work that way
the assets do get liquidated but the buying power doesn't seem to get affected.
Please help me out with this

**Comment by haxdds** [comment]
You will need to wait some time between submitting the close position request before it registers on your account's buying power.
