### ISSUE TITLE
[Bug]: TimeFrame.value()

### ISSUE THREAD

**Issue by ValerioGalanti** [alpacahq/alpaca-py#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

TimeFrame objects are not getting correctly converted for requests, for example when calling .get_stock_bars() with a StockBarsRequest object this throws an error. At the definition of the TimeFrame class, the .value(self -> str) has a typo:

return f"{self.amount}{self.unit.value}"

"unit.value" should instead be "unit_value", and this is indeed fixed by replacing this with:

return f"{self.amount}{self.unit_value}"

instead. 

### Expected Behavior

See above ^

### SDK Version I encountered this issue in

alpaca-py v0.8.2

### Steps To Reproduce

```markdown
from alpaca.data.historical import StockHistoricalDataClient
from alpaca.data.requests import StockQuotesRequest, StockBarsRequest
from alpaca.data.timeframe import TimeFrame

data_client = StockHistoricalDataClient(api_key=config.API_KEY, secret_key=config.SECRET_KEY)

stock_request = StockBarsRequest(
                    symbol_or_symbols=['TSLA'], 
                    start=dt.datetime(2022, 1, 10), 
                    end=dt.datetime(2022, 1, 11), 
                    timeframe=TimeFrame(1, 'Min')
                )

data_client.get_stock_bars(stock_request)
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by haxdds** [comment]
What version of python are you using?

**Comment by sshcli** [comment]
@ValerioGalanti in my test, it works without any problems using Alpaca 0.8.2 + Python 3.9 and 3.10

Try with the following:


```
from alpaca.data.timeframe import TimeFrame              
from alpaca.data.timeframe import TimeFrameUnit          

symbol = 'SPY'  
now = datetime.datetime.now(pytz.timezone('America/New_York'))
delta = datetime.timedelta(minutes = 15)
start = now - delta
     
sbr = StockBarsRequest(symbol_or_symbols=[symbol],timeframe=TimeFrame(1, TimeFrameUnit.Minute), start=start, end=now)
bars = data.get_stock_bars(sbr).df.sort_values(by='timestamp', ascending=False)
```

**Comment by haxdds** [comment]
Great catch @sshcli 

@ValerioGalanti The issue is occuring because you are passing in the TimeFrame unit as a string `Min` instead of TimeFrameUnit.Minute`
