### ISSUE TITLE
Improve release cadence

### ISSUE THREAD

**Issue by impredicative** [alpacahq/alpaca-py#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

What is the point of fixing issues if there is no release? There is no harm in releasing asap after a fix. I update the rest of my code multiple times a day if I have to, or as often as necessary. What's the holdup here? Releasing will keep things honest, as users can then actually test fixes, leading to further evolution of the package, otherwise it's one big lie.

**Comment by haxdds** [comment]
Hey @impredicative we've released [0.9.0](https://github.com/alpacahq/alpaca-py/releases/tag/v0.9.0).

This contains pandas v2 and some other changes. We're still working out kinks in the pydantic v2 migration.
