### ISSUE TITLE
[Bug]: "feeds" enum not properly initialized in Python 3.11

### ISSUE THREAD

**Issue by amor71** [alpacahq/alpaca-py#330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Python 3.11 changed ENUM behavior; as such, `feed` parameter is not correctly initialized.

### SDK Version I encountered this issue in

0.9.0

### Steps To Reproduce

```markdown
Install Python 3.11, try to run the examples in the documentation.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by alessiocastrica** [comment]
Hi @amor71 is this still relevant when using the latest version (v0.12) of alpaca-py? If it is could you add a reproducible example of the issue?
