### ISSUE TITLE
[Bug]: Fix docs build CI

### ISSUE THREAD

**Issue by alessiocastrica** [alpacahq/alpaca-py#339]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/alpacahq/alpaca-py/actions/runs/6251692473/job/16973361293 

### Expected Behavior

Docs should build successfully

### SDK Version I encountered this issue in

v0.10.0

### Steps To Reproduce

```markdown
Run ./tools/scripts/generate-docs.sh
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by hiohiohio** [comment]
ref. https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.protected_namespaces
