### ISSUE TITLE
[Bug]: alpaca-py throws PydanticUserError with pydantic 2.3.0

### ISSUE THREAD

**Issue by darose** [alpacahq/alpaca-py#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

My distro updated to pydantic v2.3.0 recently.  Now I'm unable to use alpaca-py.  It shows the following error:

```
    from alpaca.trading.client import TradingClient
  File "/usr/lib/python3.11/site-packages/alpaca/trading/__init__.py", line 1, in <module>
    from .client import *
  File "/usr/lib/python3.11/site-packages/alpaca/trading/client.py", line 11, in <module>
    from alpaca.trading.requests import (
  File "/usr/lib/python3.11/site-packages/alpaca/trading/requests.py", line 25, in <module>
    class ClosePositionRequest(NonEmptyRequest):
  File "/usr/lib/python3.11/site-packages/alpaca/trading/requests.py", line 35, in ClosePositionRequest
    @root_validator()
     ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/pydantic/deprecated/class_validators.py", line 228, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

### Expected Behavior

Executing ```from alpaca.trading.client import TradingClient``` should just silently succeed.

### SDK Version I encountered this issue in

This is using v0.8.0 of alpaca-py.  (I am unable to upgrade to v0.10.0 due to bug #311, which is blocking me from upgrading.)

### Steps To Reproduce

```markdown
1. Execute:  alpaca.trading.client import TradingClient
2. See the error stack trace that results.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by alessiocastrica** [comment]
Hi @darose this is expected as pydantic v2 isn't supported yet from the current released versions, we'll release a new version with pydantic v2 support soon, hopefully in that version we can also solve the other `setup.py` issue you opened.

**Comment by darose** [comment]
Looks all good!

```
$ pacman -Q python-alpaca-py
python-alpaca-py 0.11.0-1

$ python
Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from alpaca.trading.client import TradingClient
>>> 
```

Thanks much for the quick fix!
