### ISSUE TITLE
[Question]: How can I inherit the sdk's classes e.g. TradingClient?

### ISSUE THREAD

**Issue by dskarbrevik** [alpacahq/alpaca-py#355]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

I'm trying to extend the capabilities of `alpaca.trading.client.TradingClient` 

I tried to start a very simple example by creating a subclass like this:

```
class StockTrader(TradingClient):
    def __init__(self, api_key, secret_key, paper):
        super().__init__(api_key=api_key, secret_key=secret_key, paper=paper)

    def get_account(self):
        return super().get_account()
```

However when I try to use this class:

```
trader = StockTrader(api_key,secret_key,paper)
trader.get_account()
```

I get the following error:

`TypeError: TradingClient.get_account() missing 1 required positional argument: 'self'`

Is there an obvious reason why inheriting from TradingClient like this can't work?

**Comment by hiohiohio** [comment]
@dskarbrevik I can not replicate this issue in my local environment and also Google Colab.
Can you please provide more information to replicate this issue such as version of `alpaca-py` and `Python` .

Below is the code I have tested in my end with alpaca-py v0.11.0 and Python 3.10.12 / Python 3.11.5.

```python
from alpaca.trading.client import TradingClient

class StockTrader(TradingClient):
    def __init__(self, api_key, secret_key, paper):
        super().__init__(api_key=api_key, secret_key=secret_key, paper=paper)

    def get_account(self):
        return super().get_account()

api_key=<PAPER API KEY>
secret_key=<PAPER API SECRET>
paper = True

trader = StockTrader(api_key, secret_key, paper)
trader.get_account()
```

**Comment by alessiocastrica** [comment]
IMO generally this method: 
```
def get_account(self):
        return super().get_account()
```
should actually be:
```
def get_account(self):
        account =  self.get_account()
        # do something else here
        return account
```
or even better you shouldn't re-define the same method if you're not doing anything else apart from calling the method of the parent class and returning it, this way you're just polluting that class namespace with no real reason.
