### ISSUE TITLE
[Bug]: Incompatibility with Google Colab pre-installed dependencies

### ISSUE THREAD

**Issue by alessiocastrica** [alpacahq/alpaca-py#359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Google Colab:
```
from alpaca.trading.client import TradingClient
```
![image](https://github.com/alpacahq/alpaca-py/assets/104512673/76ec3d73-90b1-4139-ac3b-4173b222dab9)

### Expected Behavior

Ideally there shouldn't be any dependencies conflict with the Colab default environment.

### SDK Version I encountered this issue in

v0.12

### Steps To Reproduce

```markdown
1. Open Google Colab
2. Import anything from alpaca-py v0.11 or v0.12
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

If you do not import the default typing-extensions before you import aplaca-py, there are no errors, for example by importing the latest verion of tensorflow (instead of the default colab one):
```
!pip install alpaca-py
import tensorflow
from alpaca.trading.client import TradingClient
```
![Screenshot 2023-10-05 at 16 42 52](https://github.com/alpacahq/alpaca-py/assets/104512673/17c57ff3-6b2c-431a-a9ee-b80996db5a8d)

This behaviour is due to [pydantic >= v2 requiring yping-extensions>=4.6.1](yping-extensions>=4.6.1)

**Comment by hiohiohio** [comment]
https://colab.research.google.com/notebooks/relnotes.ipynb#scrollTo=BCnGH7WZuEoI
> tensorflow 2.13.0 -> 2.14.0
> tensorflow-probability 0.20.1 -> 0.22.0

tensorflow version was bumped to v2.14.0. However, tensorflow-probability 0.22.0 still requires typing-extensions<4.6.0.
Seems we need to wait [tensorflow-probability v0.22.1](https://github.com/tensorflow/probability/releases/tag/v0.22.1) to mark this issue resolved.

**Comment by hiohiohio** [comment]
Please let me close this issue as tensorflow-probability is upgraded to `0.23.0` on google colab.
https://github.com/googlecolab/backend-info/blob/ecfb7fb7e53069170a9f90815b95556aa6cb61ec/pip-freeze.txt#L426
