### ISSUE TITLE
[Bug]: Paper API - quantity in opened position is not the same as requested in market order

### ISSUE THREAD

**Issue by mihaiprecupetu** [alpacahq/alpaca-py#374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I open an order, the filled quantity is slightly less then the one requested.
This issue also happens when performing a HTTP rest call directly.

For example, opening BUY 0.1 BTCUSD will result in 0.09975 quantity.

### Expected Behavior

After opening order, quantity on position should be exact as requested.
After opening BUY 0.1 BTCUSD, the position should have exactly 0.1 quantity.

### SDK Version I encountered this issue in

alpaca-py==0.13.1

### Steps To Reproduce

```markdown
1. trigger a market order BUY with 0.1 qty 
2. verify quantity in account position

Code: 

import alpaca.trading.client
import alpaca.trading.requests
import alpaca.trading.enums

trading_client = alpaca.trading.client.TradingClient(
    'xxxx', 'yyyyyyy', paper=True)

# preparing market order
market_order_data = alpaca.trading.requests.MarketOrderRequest(
    symbol="BTCUSD",
    qty=0.1,
    side=alpaca.trading.enums.OrderSide.BUY,
    time_in_force=alpaca.trading.enums.TimeInForce.GTC
)

# Market order
market_order = trading_client.submit_order(
    order_data=market_order_data
)
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

![image](https://github.com/alpacahq/alpaca-py/assets/8133451/d04f4086-cf84-4bb8-adbd-e58ac0f23a84)

**Comment by hiohiohio** [comment]
@mihaiprecupetu Please check [crypto fees in the doc](https://docs.alpaca.markets/docs/crypto-fees)

> Buy ETH/USD, you receive ETH, the fee is denominated in ETH

The example in the doc is ETH though, the 0.00025 BTC seems the fee of the trade.
0.25% == 0.0025
0.1 BTC * 0.0025 = 0.00025 BTC
0.1 BTC - 0.00025 BTC = 0.09975
