### ISSUE TITLE
Broker API: Trading - Portfolio History

### ISSUE THREAD

**Issue by drew887** [alpacahq/alpaca-py#38]
Implement the Portfolio History routes as seen [here in the docs](https://alpaca.markets/docs/api-references/broker-api/trading/portfolio-history/)

Should add the following to BrokerClient:
```python
def get_portfolio_history_for_account(
        self,
        account_id: Union[UUID, str],
) -> PortfolioHistory:
    pass
```

**Comment by ryansdowning** [comment]
take
