### ISSUE TITLE
light edit for docs

### ISSUE THREAD

**Issue by taylor-bsg** [alpacahq/alpaca-py#399]
https://github.com/alpacahq/alpaca-py/blob/a41e28b72ee7b43eed45377d00186257828fbdb2/README.md?plain=1#L201

Here I suggest adding a simple line that says: "To do the same for stocks, it suffices to replace Crypto with Stock throughout the code and pass your Key and Secret into the StockHistoricalDataClient call."

**Comment by hiohiohio** [comment]
@taylor-bsg thank you for the suggestion. I have created a PR!
