### ISSUE TITLE
[Bug]: Duplicate Indicies

### ISSUE THREAD

**Issue by bossdown123** [alpacahq/alpaca-py#421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i retrieve a Barset and convert it to a DataFrame the result contains duplicated indices

### Expected Behavior

When i retrieve a Barset and convert it to a DataFrame the result should not contain duplicated indices

### SDK Version I encountered this issue in

latest at the time

### Steps To Reproduce

```markdown
def get_bars(stock):
    request_params = StockBarsRequest(
        symbol_or_symbols=stock,
        timeframe=TimeFrame(30,TimeFrameUnit('Min')),
        start=index.min(),
        end=index.max(),
        #limit=1000,
        adjustment=Adjustment.ALL,
        feed='sip'
    )
    return  client.get_stock_bars(request_params)

df = barsets.df
df = df.T[stock].T.drop(['vwap','trade_count'], axis=1)
df = df[df.index.duplicated(keep=False)]
display(df)
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

![image](https://github.com/alpacahq/alpaca-py/assets/48166550/0e11caf9-c399-494b-b2b7-e94ae7cace42)

**Comment by hiohiohio** [comment]
@bossdown123 thank you for reporting the issue. confirmed. please let me investigate and fix this issue.

**Comment by hiohiohio** [comment]
@bossdown123 we have fixed this issue. Could you please try again to confirm when you have a chance?

**Comment by bossdown123** [comment]
issue resolved

**Comment by bossdown123** [comment]
![image](https://github.com/alpacahq/alpaca-py/assets/48166550/bfa4d529-a983-4365-abde-2bf08a5982eb)
![image](https://github.com/alpacahq/alpaca-py/assets/48166550/42653d43-5725-42a0-9d80-cfa157df3967)
ive been forced to re open the issue

**Comment by bossdown123** [comment]
```

from datetime import *
index=pd.date_range(start=datetime(2020,11,1),end=datetime.now(),tz='UTC',freq='30min')
def get_bars(stock,time):
    start=time-timedelta(hours=10)
    request_params = StockBarsRequest(
        symbol_or_symbols=stock,
        timeframe=TimeFrame(30,TimeFrameUnit('Min')),
        start=start,
        end=time,
        #limit=1000,
        adjustment=Adjustment.ALL,
        feed='sip'
    )
    return  client.get_stock_bars(request_params)


```

the get bars function btw

**Comment by bossdown123** [comment]
![image](https://github.com/alpacahq/alpaca-py/assets/48166550/18a3cf43-a712-4af7-97f2-1b66ccd9f94d)
what i notice is that duplicates do not show in the same way for every stock yet you can repeatedly find them for the same request
