### ISSUE TITLE
[Bug]:README fix for market docs URL 

### ISSUE THREAD

**Issue by desavera** [alpacahq/alpaca-py#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

As simple as pointing to an updated URL : https://docs.alpaca.markets/ for the market doc link.

### Expected Behavior

The URL for the market doc changed to : https://docs.alpaca.markets/

### SDK Version I encountered this issue in

LATEST

### Steps To Reproduce

```markdown
just open the README and the link for the market doc is a 404
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

Keep on ROCKING !!!

**Comment by hiohiohio** [comment]
@desavera Thank you for the report! Fixed.
