### ISSUE TITLE
[Bug]: All example notebooks appear to be broken

### ISSUE THREAD

**Issue by sdmorrey** [alpacahq/alpaca-py#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"An error occured" is the only message I get when viewing example notebooks such as the one here: https://github.com/alpacahq/alpaca-py/blob/master/examples/crypto-trading-basic.ipynb

### Expected Behavior

They're your example code. It would be helpful if they worked.

### SDK Version I encountered this issue in

current

### Steps To Reproduce

```markdown
Go here https://github.com/alpacahq/alpaca-py/blob/master/examples/crypto-trading-basic.ipynb

See that it gives an error and nothing more.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

### Anything else?

I'd like to learn this API. Having the publicly visible API examples not working is disappointing and makes me worried about trading here with real money. I hope this was just an oversight.

**Comment by hiohiohio** [comment]
@sdmorrey thank you for the reporting. Seems github's preview feature has something wrong currently. As a workaround, you could open the notebook in a Google Colab by clicking `Open in Colab` button in the below page [1].

*1 https://github.com/alpacahq/alpaca-py/tree/master/examples

**Comment by hiohiohio** [comment]
@sdmorrey seems this issue is resolved in github side.

**Comment by hiohiohio** [comment]
Please let me close this issue as github fixed it.
