### ISSUE TITLE
[Bug]: Fix broken link in About section of repo

### ISSUE THREAD

**Issue by impredicative** [alpacahq/alpaca-py#463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "About" pane of the repo currently has a link to https://docs.alpaca.markets/docs/getting-started-1 which is broken. It would help to replace this broken link with a link that actually works, e.g. https://pypi.org/project/alpaca-py/

### SDK Version I encountered this issue in

NA

### Steps To Reproduce

```markdown
1. open eyes.
2. open repo.
3. click link.
4. see error.
```

### Filled out the Steps to Reproduce section?

- [X] I have entered valid steps to reproduce my issue or have attached a minimally reproducible case in code that shows my issue happening; and understand that without this my issue will be flagged as invalid and closed after 30 days.

**Comment by hiohiohio** [comment]
@impredicative thank you very much for the report! I have updated to https://alpaca.markets/sdks/python/getting_started.html
