### ISSUE TITLE
[Question]: Question about GetPortfolioHistoryRequest

### ISSUE THREAD

**Issue by miguelsostin** [alpacahq/alpaca-py#533]
### Question form pre-submit checklist.

- [X] I have searched the existing issues to ensure there isn't already an issue about this question.
- [X] My question has to do with the Python SDK and isn't a general question about the API. (If it is please open your issue [here](https://github.com/alpacahq/Alpaca-API))
- [X] My question isn't about how to do a specific algorithm or asking for trade advice (answers to these are outside the scope of this repo).

### Question

 The class GetPortfolioHistoryRequest seams to be defined, but there is no get method implemented in the TradingClient class. Am I missing something?

**Comment by hiohiohio** [comment]
You are right. Currently it is only implemented in the BrokerClient. And it seems we just need to add similar method into TradingClient.
