### ISSUE TITLE
Trading API: Account Activities

### ISSUE THREAD

**Issue by haxdds** [alpacahq/alpaca-py#54]
Implement routes defined in Trading API [account activities docs](https://alpaca.markets/docs/api-references/trading-api/account-activities/). 

```python

def get_account_activities_by_type(self, type: ActivityType, request: GetAccountActivitiesByTypeRequest) -> List[AccountActivity]:
   pass

def get_account_activities(self, request: GetAccountActivitiesRequest) -> List[AccountActivity]:
   pass

```

**Comment by yohay13** [comment]
Is this going to happen at some point? Or no one cares about their P&L per activity?

**Comment by sshcli** [comment]
I have opened a related issue here https://github.com/alpacahq/alpaca-py/issues/192 
Any status is appreciated

**Comment by PBbanana** [comment]
is it me, or is this only available in the Broker API?
