### ISSUE TITLE
Trading API: Portfolio History

### ISSUE THREAD

**Issue by haxdds** [alpacahq/alpaca-py#55]
Implement routes defined by Trading API [portfolio history docs](https://alpaca.markets/docs/api-references/trading-api/portfolio-history/). 

```python

def get_portfolio_history(self, request: GetPortfolioHistoryRequest) -> PortfolioHistory:
   pass

```

**Comment by ryansdowning** [comment]
I have implemented this for the broker client here: https://github.com/ryansdowning/alpaca-py/blob/ryan/broker-sdk-trading/alpaca/broker/client.py#L670

and added the models to common in `trading.py` and `requests.py` here: https://github.com/ryansdowning/alpaca-py/tree/ryan/broker-sdk-trading/alpaca/common/models

**Comment by haxdds** [comment]
Hey Ryan, your code looks good. We're working on issue #56 so we can unblock all the Trading API and Broker API endpoints that depend on these objects models. Maybe you can submit a PR for `Position` and `Portfolio History` since you have those complete and we can cross those models off the list from #56 .
